[package]
name = "nu-space"
version = "0.62.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.18.0"
nu-protocol = { path = "../nu-protocol", version = "0.62.1" }
crossterm = "0.24.0"
